query getCharacteristicTypes {
  characteristicTypes {
    id
    name
    minLimit
    maxLimit
  }
}

query getCharacteristics {
  characteristics {
    id
    name
    characteristicType {
      id
    }
    characteristicTypeId
  }
}

query getTriggerWarnings {
  triggerWarnings {
    id
    name
  }
}

query getThemes {
  themes {
    id
    name
    default
    enabled
    useDefaultFrom
    useDefaultTo
    details
  }
}

query getFandoms {
  fandoms {
    id
    name
    slug
  }
}
