[tool.poetry]
name = "hpfserver"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
django = "^5.2.6"
django-extensions = "^4.1"
pillow = "11.3.0"
django-cors-headers = "^4.9.0"
django-filter = "^25.1"
gunicorn = "^23.0.0"
docx2python = "*"
django-ordered-model = "^3.7.4"
psycopg = "^3.2.10"
django-mptt = "^0.18.0"
django-polymorphic-tree = "^2.1"
setuptools = "^78.1.0"
strawberry-graphql-django = "0.75.1"
strawberry-django-extras = "0.2.6"
django-polymorphic = "4.1.0"
python-slugify = "^8.0.4"

[tool.poetry.group.dev.dependencies]
faker = "*"
ruff = "^0.15.1"
ipython = "^9.10.0"

[tool.ruff.lint]
exclude = ["**/tests/**"]
select = ["E4", "E7", "E9", "F", "ANN", "COM", "EM", "INP", "T20", "Q", "TC", "PTH", "W"]
ignore = ["ANN002", "ANN003", "ANN401", "Q001"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
