[tool.poetry]
name = "hpfserver"
version = "0.1.0"
description = ""
authors = ["PierreMDL <pierre@catecut.com>"]
readme = "À lire"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
django = "*"
djangorestframework = "*"
django-extensions = "*"
djangorestframework-simplejwt = "*"
pillow = "*"
django-cors-headers = "*"
django-filter = "*"
gunicorn = "*"
docx2python = "*"
django-ordered-model = "*"
drf-extra-fields = "*"
django-mptt = "*"
djangorestframework-recursive = "*"
django-polymorphic-tree = "*"
django-rest-polymorphic = "*"
graphene-django = "^3.2.2"
faker = "^26.0.0"

[tool.poetry.group.dev.dependencies]
drf-spectacular = "^0.27.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
