query getFandomDetails($fandomSlug: String!) {
  fandom: fandomBySlug(slug: $fandomSlug) {
    id
    name
    slug
  }
}

query getFandomNews {
  newsArticles(pagination: { limit: 10 }, order: { postDate: DESC }) {
    totalCount
    pageInfo {
      limit
      offset
    }
    results {
      id
      title
      postDate
      content
      contentImages {
        id
        src
      }
      commentCount
      authors {
        ...BaseUserInfo
      }
    }
  }
}

query getFandomFictions($filters: FictionFilters) {
  fictions(pagination: { limit: 10 }, filters: $filters, order: { lastUpdateDate: DESC }) {
    totalCount
    results {
      id
      title
      summary
      creationUser {
        ...BaseUserInfo
      }
      authors {
        ...BaseUserInfo
      }
      chapters(pagination: { limit: 1 }) {
        results {
          id
          title
        }
      }
      characteristics {
        id
        name
        characteristicTypeId
      }
      fandoms {
        id
        name
        slug
      }
    }
  }
}
