query getNewsDetails($newsId: ID) {
  newsArticle(pk: $newsId) {
    id
    title
    postDate
    content
    contentImages {
      id
      src
    }
    commentCount
    authors {
      ...BaseUserInfo
    }
    comments {
      id
      author {
        ...BaseUserInfo
      }
      content
      postDate
    }
  }
}
