query getChapterDetail($chapterId: ID) {
  chapter(pk: $chapterId) {
    id
    title
    order
    text
    startNote
    endNote
    reviewCount
  }
}

query getChapterReviews($filters: ChapterReviewFilters, $pagination: OffsetPaginationInput) {
  chapterReviews(filters: $filters, pagination: $pagination, order: { publicationDate: DESC }) {
    totalCount
    pageInfo {
      limit
      offset
    }
    results {
      id
      grading
      text
      authors {
        id
        username
      }
    }
  }
}

mutation createChapterReview($chapterId: Int!, $chapterReviewData: ReviewInput!) {
  createChapterReview(chapterId: $chapterId, reviewData: $chapterReviewData) {
    id
  }
}
