{
    paginatedCharacteristics {
        current
        count
        results {
            id
            name
            description
            characteristicTypeId
            parentId
        }
    }
}
