query getCharacteristicTypes {
    characteristicTypes {
        id
        name
        minLimit
        maxLimit
    }
}

query getCharacteristics {
    characteristics {
        id
        name
        characteristicType {
            id
        }
    }
}
