{
    fictions {
        id
        title
        characteristics {
            id
            name
            characteristicType {
                id
                name
            }
        }
    }
}
