{
    paginatedFictions {
        current
        count
        results {
            id
            title
            summary
            lastUpdateDate
            creationDate
            wordCount
            readCount
            chapterCount
            reviewCount
            average
            authors {
                id
                username
            }
            characteristics {
                id
                name
                characteristicTypeId
            }
        }
    }
}
