{
    paginatedNewsArticles {
        current
        count
        results {
            id
            title
            content
            postDate
            creationUser {
                id
                username
            }
            authors {
                id
                username
            }
        }
    }
}
