{
    paginated_news {
        current
        count
        results {
            id
            title
            content
            post_date
            creation_user {
                id
                username
            }
            authors {
                id
                username
            }
        }
    }
}
